### ISSUE TITLE
USER STORY: Search for Jobs

### ISSUE THREAD

**Issue by FlashDrag** [FlashDrag/get-job#2]
Epic: #1 

### Description
As a **Job Seeker** I can **search for jobs** so that **I can find an appropriate job**.

### Tasks
- [x] Add search bar with `Find Job` btn
- [x] Implement Search by job title, e.g. software engineer
- [ ] Expand search options, add area to the search panel on home page

**Comment by FlashDrag** [comment]
The area field has not been added to the search panel on the home page because on small screens it will have to be split into two lines, which breaks the original design
