### ISSUE TITLE
USER STORY: App purpose

### ISSUE THREAD

**Issue by FlashDrag** [FlashDrag/get-job#24]
Epic: #1 

### Description
As a **Jobseeker** I want to be able to **see the purpose of the app** so that **I can decide if it is useful for me**.

### Tasks
**Hero Section**:
- [x] - Add Call to Action Headings
- [x] - Add Image that conveys the main message of the app
- [x] -  Add `Create Resume` btn
