### ISSUE TITLE
USER STORY: Apply for a job

### ISSUE THREAD

**Issue by FlashDrag** [FlashDrag/get-job#4]
Epic: #29 #42  
### Description
As a **Job Seeker** I can **apply for a job** so that **I can get a job**.

### Tasks
- [x] Create `Apply` btn with link to the application form
- [x] Add the btn to the job cards of the list of the latest vacancies on the home page to allow jobseekers apply for a job quickly
- [x] Add the btn to the job cards of the full list of jobs
- [x] Add the btn to the job detailed page
