### ISSUE TITLE
USER STORY: Search bar on the page of all jobs

### ISSUE THREAD

**Issue by FlashDrag** [FlashDrag/get-job#53]
Epic: #42 

### Description
As a Jobseeker I want to be able to use the search bar on the page of the full list of jobs.

### Tasks
- [x] Add a search bar to the aside panel of search bar on the page of all jobs
- [x] Implement a search form the panel
- [x] Implement searching functionality
