### ISSUE TITLE
USER STORY: NavBar

### ISSUE THREAD

**Issue by FlashDrag** [FlashDrag/get-job#87]
Epic: #1 

### Description
As a Jobseeker I want to be able to see the navigation bar so that I can easily navigate the app.

### Tasks
- [x] Logo
- [x] Toogle btn: jobseeker/employer
- [x] Notification icon
- [x] Sign In/Sign Up btn or link
- [x] Profile icon
- [x] Change style of the jobseeker/employer btn group
- [x] Increase size of Sign In/Sign and Profile icons
- [x] Change colors from to purple
